services:
  - type: web
    name: routemapper-web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app

  - type: worker
    name: routemapper-worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python Worker.py
