services:
  - type: web
    name: routemapper
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    plan: free

  - type: worker
    name: worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python worker.py
    plan: free
